import { v4 as uuidv4 } from "uuid";

const Users = [
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "/Assets/Images/aiony-haust.jpg",
    city: "Dhaka",
    country: "Bangladesh",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Fashion",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "RHShoumik",
    img: "./Assets/Images/alex-suprun-ZHvM3XIOHoE-unsplash.jpg",
    city: "London",
    country: "UK",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Photography",
    gender: "Male",
    joinedDate: "May 29th, 2022",
  },
  {
    id: uuidv4(),
    name: "Jonathan Smith",
    img: "./Assets/Images/ana-itonishvili-Fyl8sMC2j2Q-unsplash.jpg",
    city: "Lahore",
    country: "Pakisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Ragib",
    img: "./Assets/Images/avater.jpg",
    city: "Dhaka",
    country: "Bangladesh",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Entertainment",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Hassan",
    img: "./Assets/Images/ben-den-engelsen-YUu9UAcOKZ4-unsplash.jpg",
    city: "Los Angels",
    country: "America",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Streaming",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Shoumik",
    img: "./Assets/Images/brantley-neal-UVUMHL-DzVM-unsplash.jpg",
    city: "New York",
    country: "US",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Travel",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Brooke Cagle",
    img: "./Assets/Images/brooke-cagle-Nm70URdtf3c-unsplash.jpg",
    city: "Toronto",
    country: "Canada",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Streaming",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Christina",
    img: "./Assets/Images/christina-wocintechchat-com-0Zx1bDv5BNY-unsplash.jpg",
    city: "Lahore",
    country: "Pakisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Education",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Christopher",
    img: "./Assets/Images/christopher-campbell-rDEOVtE7vOs-unsplash.jpg",
    city: "Kalkata",
    country: "India",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Photography",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Ed-Haust",
    img: "./Assets/Images/edward-cisneros-_H6wpor9mjs-unsplash.jpg",
    city: "Victoria",
    country: "Canada",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Education",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/foto-sushi-6anudmpILw4-unsplash.jpg",
    city: "Panjab",
    country: "India",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Cooking",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/gabriel-silverio-u3WmDyKGsrY-unsplash.jpg",
    city: "New York",
    country: "US",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Technology",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/harps-joseph-tAvpDE7fXgY-unsplash.jpg",
    city: "Kabul",
    country: "Afganisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Cooking",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Jd Manson",
    img: "./Assets/Images/jd-mason-2oUiUu5QAys-unsplash.jpg",
    city: "Kalkata",
    country: "India",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Travel",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Jonathan Zerger",
    img: "./Assets/Images/jonathan-zerger-owd6tarUcac-unsplash.jpg",
    city: "New York",
    country: "US",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Education",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/joseph-gonzalez-iFgRcqHznqg-unsplash.jpg",
    city: "Bogura",
    country: "Bangladesh",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Streaming",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Julian Wan",
    img: "./Assets/Images/julian-wan-WNoLnJo7tS8-unsplash.jpg",
    city: "Toronto",
    country: "Canada",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Travel",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aysha Khatun",
    img: "./Assets/Images/jurica-koletic-7YVZYZeITc8-unsplash.jpg",
    city: "London",
    country: "UK",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Technology",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Smith John",
    img: "./Assets/Images/leio-mclaren-L2dTmhQzx4Q-unsplash.jpg",
    city: "Kabul",
    country: "Afganisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Cooking",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/luis-villasmil-Z4rqvRpRj38-unsplash.jpg",
    city: "London",
    country: "America",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Photography",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/michael-dam-mEZ3PoFGs_k-unsplash.jpg",
    city: "Kalkata",
    country: "India",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Education",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/prince-akachi-l3IHXOdMyHQ-unsplash.jpg",
    city: "Dhaka",
    country: "Bangladesh",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Cooking",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/roland-cousins-3GTHyh2lo9o-unsplash.jpg",
    city: "London",
    country: "UK",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Photography",
    gender: "Female",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/romina-farias-BsZ71j4i_m4-unsplash.jpg",
    city: "Lahore",
    country: "Pakisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/tyler-nix-X2YO8KFxgEM-unsplash.jpg",
    city: "Dhaka",
    country: "Bangladesh",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Fashion",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/usman-yousaf-q2q5CdLuWnI-unsplash.jpg",
    city: "New York",
    country: "US",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Streaming",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/vince-veras-AJIqZDAUD7A-unsplash.jpg",
    city: "Lahore",
    country: "Pakisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Entertainment",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/vince-veras-AJIqZDAUD7A-unsplash.jpg",
    city: "Kabul",
    country: "Afganisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Streaming",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/warren-wong-VVEwJJRRHgk-unsplash.jpg",
    city: "Austin",
    country: "US",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Cooking",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
  {
    id: uuidv4(),
    name: "Aiony-Haust",
    img: "./Assets/Images/aiony-haust.jpg",
    city: "Lahore",
    country: "Pakisthan",
    social: {
      facebook: "#",
      instagram: "#",
      linkedIn: "#",
      twitter: "#",
    },
    phone: "+123 456 789",
    email: "b@beyonce.com",
    followers: "12k",
    category: "Travel",
    gender: "Male",
    joinedDate: "July 26th, 2022",
  },
];
export default Users;
